import {
  SiConfluence,
  SiCursor,
  SiDocker,
  SiFastapi,
  SiFirebase,
  SiFlask,
  SiGit,
  SiGithub,
  SiGooglecloud,
  SiJavascript,
  SiJira,
  SiJupyter,
  SiLinux,
  SiMongodb,
  SiNextdotjs,
  SiNodedotjs,
  SiNumpy,
  SiPandas,
  SiPostgresql,
  SiPython,
  SiPytorch,
  SiR,
  SiReact,
  SiScikitlearn,
  SiSwift,
  SiTailwindcss,
  SiTensorflow,
  SiTerraform,
  SiTypescript,
} from "react-icons/si";
import { Cloud, Code, Database, Box } from "lucide-react";

const map = {
  python: SiPython,
  typescript: SiTypescript,
  javascript: SiJavascript,
  react: SiReact,
  gcp: SiGooglecloud,
  postgres: SiPostgresql,
  docker: SiDocker,
  github: SiGithub,
  git: SiGit,
  vscode: Code,
  cursor: SiCursor,
  datagrip: Box,
  next: SiNextdotjs,
  tailwind: SiTailwindcss,
  node: SiNodedotjs,
  flask: SiFlask,
  fastapi: SiFastapi,
  tensorflow: SiTensorflow,
  pytorch: SiPytorch,
  sklearn: SiScikitlearn,
  pandas: SiPandas,
  numpy: SiNumpy,
  jupyter: SiJupyter,
  aws: Cloud,
  terraform: SiTerraform,
  mongodb: SiMongodb,
  firebase: SiFirebase,
  linux: SiLinux,
  jira: SiJira,
  confluence: SiConfluence,
  swift: SiSwift,
  r: SiR,
  sql: Database,
};

const aliases = {
  Python: "python",
  TypeScript: "typescript",
  JavaScript: "javascript",
  React: "react",
  "Google Cloud": "gcp",
  PostgreSQL: "postgres",
  "Cloud SQL": "postgres",
  Docker: "docker",
  GitHub: "github",
  "Git / GitHub": "github",
  "VS Code": "vscode",
  Cursor: "cursor",
  DataGrip: "datagrip",
  "Next.js": "next",
  "Tailwind CSS": "tailwind",
  Tailwind: "tailwind",
  "Node.js": "node",
  Flask: "flask",
  FastAPI: "fastapi",
  TensorFlow: "tensorflow",
  PyTorch: "pytorch",
  "Scikit-learn": "sklearn",
  Pandas: "pandas",
  NumPy: "numpy",
  Jupyter: "jupyter",
  AWS: "aws",
  "Microsoft 365": "vscode",
  Terraform: "terraform",
  MongoDB: "mongodb",
  Firebase: "firebase",
  Linux: "linux",
  Jira: "jira",
  Confluence: "confluence",
  Swift: "swift",
  R: "r",
  SQL: "sql",
};

export const BrandIcon = ({ name, className = "h-5 w-5" }) => {
  const key = map[name] ? name : aliases[name];
  const Icon = map[key] || Database;
  return <Icon className={className} aria-hidden="true" />;
};
