/** @typedef {'live' | 'professional' | 'in-development'} ModelState */
/** @typedef {'real' | 'synthetic' | 'open'} DatasetKind */

/**
 * Hand-authored from committed project pages and public READMEs.
 * A row without a benchmark is shown muted on the scorecard.
 */
export const metrics = [
  {
    project: "IMDB Sentiment",
    slug: "imdb-sentiment",
    model: "Logistic Regression",
    task: "Binary review sentiment",
    metric: "Accuracy",
    value: 0.8845,
    valueLabel: "88.45%",
    benchmark: { name: "Class balance (~50%)", value: 0.5, valueLabel: "~50%" },
    dataset: "open",
    state: "live",
  },
  {
    project: "IMDB Sentiment",
    slug: "imdb-sentiment",
    model: "Logistic Regression",
    task: "Binary review sentiment",
    metric: "F1",
    value: 0.8835,
    valueLabel: "88.35%",
    benchmark: { name: "Class balance", value: 0.5, valueLabel: "~50%" },
    dataset: "open",
    state: "live",
  },
  {
    project: "IMDB Sentiment",
    slug: "imdb-sentiment",
    model: "Logistic Regression",
    task: "Binary review sentiment",
    metric: "ROC AUC",
    value: 0.9552,
    valueLabel: "95.52%",
    benchmark: { name: "Chance", value: 0.5, valueLabel: "0.50" },
    dataset: "open",
    state: "live",
  },
  {
    project: "IMDB Sentiment",
    slug: "imdb-sentiment",
    model: "Naive Bayes",
    task: "Binary review sentiment",
    metric: "Accuracy",
    value: 0.8521,
    valueLabel: "85.21%",
    benchmark: { name: "Class balance (~50%)", value: 0.5, valueLabel: "~50%" },
    dataset: "open",
    state: "live",
  },
  {
    project: "IMDB Sentiment",
    slug: "imdb-sentiment",
    model: "Random Forest",
    task: "Binary review sentiment",
    metric: "Accuracy",
    value: 0.8431,
    valueLabel: "84.31%",
    benchmark: { name: "Class balance (~50%)", value: 0.5, valueLabel: "~50%" },
    dataset: "open",
    state: "live",
  },
  {
    project: "IMDB Sentiment",
    slug: "imdb-sentiment",
    model: "Gradient Boosting",
    task: "Binary review sentiment",
    metric: "Accuracy",
    value: 0.8069,
    valueLabel: "80.69%",
    benchmark: { name: "Class balance (~50%)", value: 0.5, valueLabel: "~50%" },
    dataset: "open",
    state: "live",
  },
  {
    project: "IMDB Sentiment",
    slug: "imdb-sentiment",
    model: "DistilBERT (no extra training)",
    task: "Zero-shot / off-the-shelf sentiment",
    metric: "Accuracy",
    value: 0.836,
    valueLabel: "83.60%",
    benchmark: { name: "Best sklearn (LR 88.45%)", value: 0.8845, valueLabel: "88.45%" },
    dataset: "open",
    state: "live",
    note: "Off-the-shelf transformer, not fine-tuned on this split.",
  },
  {
    project: "IMDB Sentiment",
    slug: "imdb-sentiment",
    model: "Corpus",
    task: "Data scale",
    metric: "Reviews",
    value: 50000,
    valueLabel: "50,000",
    dataset: "open",
    state: "live",
  },
];
