export const skills = [
  { name: "Python", category: "Modelling", years: 5, note: "ML pipelines, APIs, notebooks" },
  { name: "scikit-learn", category: "Modelling", years: 3, note: "Classical ML, evaluation, ensembles" },
  { name: "TensorFlow", category: "Modelling", years: 2, note: "Deep learning with Keras" },
  { name: "PyTorch", category: "Modelling", years: 1, note: "Research-style neural nets" },
  { name: "Hugging Face", category: "Modelling", years: 1, note: "Transformers, inference APIs" },
  { name: "LangChain", category: "Modelling", years: 1, note: "LLM app composition / RAG" },
  { name: "Pandas", category: "Data", years: 3, note: "Wrangling and analysis" },
  { name: "NumPy", category: "Data", years: 3, note: "Numerical computing" },
  { name: "R", category: "Data", years: 2, note: "USDA LULC accuracy scripts" },
  { name: "SQL", category: "Data", years: 3, note: "Relational queries" },
  { name: "Google Earth Engine", category: "Data", years: 2, note: "Fiji water-quality monitoring" },
  { name: "KNIME", category: "Data", years: 1, note: "Predictive maintenance workflow" },
  { name: "JavaScript", category: "Engineering", years: 4, note: "ES6+, React apps" },
  { name: "TypeScript", category: "Engineering", years: 2, note: "Typed frontends" },
  { name: "React", category: "Engineering", years: 2, note: "This site, MindSight" },
  { name: "Next.js", category: "Engineering", years: 1, note: "Full-stack React" },
  { name: "HTML/CSS", category: "Engineering", years: 4, note: "Responsive UI" },
  { name: "Tailwind CSS", category: "Engineering", years: 2, note: "Utility-first styling" },
  { name: "Flask / FastAPI", category: "Engineering", years: 2, note: "Python HTTP services" },
  { name: "Node.js", category: "Engineering", years: 2, note: "JS backends" },
  { name: "Java", category: "Engineering", years: 3, note: "OOP coursework and apps" },
  { name: "Godot", category: "Engineering", years: 1, note: "Quanta 4.7 prologue" },
  { name: "AWS", category: "Delivery", years: 2, note: "EC2, S3, Lambda, SageMaker" },
  { name: "GCP", category: "Delivery", years: 1, note: "Cloud + AI workloads" },
  { name: "Docker", category: "Delivery", years: 2, note: "Containerized services" },
  { name: "Terraform", category: "Delivery", years: 1, note: "Infrastructure as code" },
  { name: "CI/CD", category: "Delivery", years: 2, note: "Automated test and deploy" },
  { name: "Git / GitHub", category: "Delivery", years: 4, note: "Version control" },
  { name: "Streamlit", category: "Delivery", years: 2, note: "Public ML demos" },
  { name: "MongoDB", category: "Delivery", years: 1, note: "Document stores" },
  { name: "Firebase", category: "Delivery", years: 2, note: "Auth and hosting" },
];

export const skillCategories = ["Modelling", "Data", "Engineering", "Delivery"];

export const featuredSkillNames = [
  "Python",
  "scikit-learn",
  "React",
  "SQL",
  "Docker",
  "Hugging Face",
];
